# Generated by Django 4.1.6 on 2023-03-01 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('supers', models.IntegerField()),
                ('frames', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('med_name', models.CharField(max_length=50)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hive_management.hive')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hive_management.hive')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('queen', models.BooleanField()),
                ('eggs', models.BooleanField()),
                ('open_brood', models.BooleanField()),
                ('sealed_brood', models.BooleanField()),
                ('honey', models.CharField(max_length=255)),
                ('varroa', models.CharField(max_length=255)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hive_management.hive')),
            ],
        ),
    ]
