# Generated by Django 4.1.6 on 2023-03-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive_management', '0003_alter_hive_color_alter_hive_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive',
            name='color',
            field=models.CharField(default='#00ff3f', max_length=7, verbose_name='Color'),
        ),
    ]
