# Generated by Django 4.1.6 on 2023-03-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive_management', '0004_alter_hive_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
