# Generated by Django 4.1.6 on 2023-03-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive_management', '0005_alter_note_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='purpose',
            field=models.CharField(default='Honey', max_length=50, verbose_name='Purpose'),
        ),
        migrations.AddField(
            model_name='hive',
            name='strength',
            field=models.IntegerField(default=90, verbose_name='Strength'),
        ),
    ]
