# Generated by Django 4.1.6 on 2023-03-07 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive_management', '0006_hive_purpose_hive_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive',
            name='strength',
            field=models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Strength'),
        ),
    ]
