# Generated by Django 4.1.6 on 2023-03-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive_management', '0007_alter_hive_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
