# Generated by Django 4.1.6 on 2023-03-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive_management', '0008_alter_inspection_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='created_on',
            field=models.DateField(),
        ),
    ]
